### ISSUE TITLE
Урок №13 (ERC20) Ошибка в transferFrom

### ISSUE THREAD

**Issue by WithVery** [bodrovis-learning/Solidity-YT-Series#1]
function transferFrom(address sender, address recipient, uint amount) public enoughTokens(sender, amount) {
...
        allowances[sender][recipient] -= amount; // error!

Должно быть
        allowances[sender][msg.sender] -= amount;
Т.к. именно оригинатор транзацкии и есть посредник, которому разрешили перевести токены от sender к recipient.

**Comment by bodrovis** [comment]
Ага, это правда. Кто-то уже просил исправить, но я забыл :) Сейчас сделаем
